### ISSUE TITLE
How to Switch betweeb spindle and laser?

### ISSUE THREAD

**Issue by mmb18021957** [Eisbaeeer/Laser_grbl_Mega2560#1]
I dont know how to switch between spindle and laser

**Comment by Eisbaeeer** [comment]
You have to compile the code and upload it to the Mega. After that, you can switch between grbl and Estlcam by reprogramming with Estlcam. Estlcam will backing up the grbl from controller and write the estlcam program on the controller. If you will switch to grbl back, you must select restore program, then estlcam will rewrite the grbl back to controller.

**Comment by Eisbaeeer** [comment]
Hab eine README.MD hinzugefügt. Dort ist beschrieben, wie man umschaltet.
