### ISSUE TITLE
Select gear 4,5,6 umbelegen mit Auswahl z,y,x. Welches Programm ist zu ändern und wo?

### ISSUE THREAD

**Issue by mmb18021957** [Eisbaeeer/Laser_grbl_Mega2560#2]
Ich möchte die Leitungen SelectGear 4,5,6 mit Auswahl z,y,x belegen. Dafür müsste der code v zb eisbaeer grbl1.1 https://github.com/Eisbaeeer/Laser_grbl_Mega2560
Geändert werden. Kennt sich jemand so gut aus die zu ändernden Zeilen zu finden ? Oder gibt es eine andere Möglichkeit ?

**Comment by Eisbaeeer** [comment]
Hi. Schau dir mal die cpu_map.h an. Da solltest du fündig werden.
https://github.com/Eisbaeeer/Laser_grbl_Mega2560/blob/main/grbl/cpu_map.h

**Comment by mmb18021957** [comment]
DankeVon meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [Eisbaeeer/Laser_grbl_Mega2560] Select gear 4,5,6 umbelegen mit Auswahl z,y,x. Welches Programm ist zu ändern und wo? (#2)Von: Lars Weimar An: Eisbaeeer/Laser_grbl_Mega2560 Cc: mmb18021957 ,Author 

Hi. Schau dir mal die cpu_map.h an. Da solltest du fündig werden.

https://github.com/Eisbaeeer/Laser_grbl_Mega2560/blob/main/grbl/cpu_map.h



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/Eisbaeeer/Laser_grbl_Mega2560/issues/2#issuecomment-880113604",

"url": "https://github.com/Eisbaeeer/Laser_grbl_Mega2560/issues/2#issuecomment-880113604",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
